#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../power-apps-cli/dist/Bin.js" "$@"
else
  exec node  "$basedir/../../../power-apps-cli/dist/Bin.js" "$@"
fi
# cmd-shim-target=/Users/shambhutiwary/Desktop/Developer/codeapp/node_modules/.pnpm/@microsoft+power-apps@1.1.3_tslib@2.8.1/node_modules/@microsoft/power-apps-cli/dist/Bin.js
