/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as OrdersListRouteImport } from './routes/orders/list'
import { Route as OrdersCreateRouteImport } from './routes/orders/create'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersListRoute = OrdersListRouteImport.update({
  id: '/orders/list',
  path: '/orders/list',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCreateRoute = OrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
  '/orders/list': typeof OrdersListRoute
  '/api/': typeof ApiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
  '/orders/list': typeof OrdersListRoute
  '/api': typeof ApiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
  '/orders/list': typeof OrdersListRoute
  '/api/': typeof ApiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders/$orderId'
    | '/orders/create'
    | '/orders/list'
    | '/api/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orders/$orderId' | '/orders/create' | '/orders/list' | '/api'
  id:
    | '__root__'
    | '/'
    | '/orders/$orderId'
    | '/orders/create'
    | '/orders/list'
    | '/api/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersCreateRoute: typeof OrdersCreateRoute
  OrdersListRoute: typeof OrdersListRoute
  ApiIndexRoute: typeof ApiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/list': {
      id: '/orders/list'
      path: '/orders/list'
      fullPath: '/orders/list'
      preLoaderRoute: typeof OrdersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/create': {
      id: '/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof OrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersCreateRoute: OrdersCreateRoute,
  OrdersListRoute: OrdersListRoute,
  ApiIndexRoute: ApiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
